src/java/controller/ProfessorController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controller;

import db.DAOFactory;

import db.daoimplementation.ProfessorDAOImpl;
import db.daointerface.ProfessorDAO;
import db.model.TbProfessor;
import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.event.ActionEvent;

/**
 *
 * @author admin
 */
@ManagedBean(name = "profController")
@SessionScoped
public class ProfessorController {

    private String mensagem = "";
    private boolean alunoInserido = false;
    private TbProfessor professor = new TbProfessor();

    public void inserirProfessor() {
        ProfessorDAO p = DAOFactory.getProfessorDAO();
        p.inserirProfessor(this.professor);
        if (professor != null && professor.getNrCpf()!= null) {
            this.setMensagem("PRofessor " + this.professor.getNmProfessor() + ", com o CPF " + this.professor.getNrCpf()+ " inserido com sucesso!");
        }
    }

    public void excluirProfessor(ActionEvent event) {
        String nrCpf = "";
        nrCpf = (String) event.getComponent().getAttributes().get("numeroCpf");
        TbProfessor excluir = new TbProfessor();
        excluir.setNrCpf((nrCpf));
        ProfessorDAO p = DAOFactory.getProfessorDAO();
        if (p.delteProfessor(excluir)) {
            this.setMensagem("Professor " + this.professor.getNmProfessor()+ ", com cpf " + this.professor.getNrCpf()+ " EXCLUÍDO!");
        }
    }

    public void selecionarProfessor(ActionEvent event) {
        String nrCpf= "";
        nrCpf = (String) event.getComponent().getAttributes().get("numeroCpf");
        TbProfessor selecionar = new TbProfessor();
        selecionar.setNrCpf((nrCpf));
        System.out.println(selecionar);
        ProfessorDAO p = DAOFactory.getProfessorDAO();
        TbProfessor retorno = p.selecionarProfessor(selecionar);
        System.out.println(retorno);
        if (retorno != null) {
            this.professor= retorno;
            this.setMensagem("Professor " + this.professor.getNmProfessor()+ ", com CPF" + this.professor.getNrCpf()+ " selecionado!");
        }

    }

    public boolean isAlunoInserido() {
        return alunoInserido;
    }

    public void setAlunoInserido(boolean alunoInserido) {
        this.alunoInserido = alunoInserido;
    }

    public List<TbProfessor> getProfessoresCadastrados() {
        return new ProfessorDAOImpl().selecionarProfessores(null);
    }

    public void atualizarProfessor() {
        ProfessorDAO a = DAOFactory.getProfessorDAO();
        a.modificarProfessor(professor);
        if (professor != null && professor.getNrCpf()!= null) {
            this.setAlunoInserido(true);
            this.setMensagem("Professor " + this.professor.getNmProfessor()+ ", com CPF " + this.professor.getNrCpf()+ " atualizado com sucesso!");
        }
    }

    public String getMensagem() {
        return mensagem;
    }

    public void setMensagem(String mensagem) {
        this.mensagem = mensagem;
    }

    public TbProfessor getProfessor() {
        return professor;
    }

    public void setProfessor(TbProfessor professor) {
        this.professor = professor;
    }


}

web/section/professor/cadastro.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">
    <script>
        setTimeout(function () {
            document.getElementById('frmCadastroAluno:lblMensagem').style.display = 'none';
        }, 3000);
    </script>
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        <h:form id="frmCadastroAluno">
            Cadastro de Professores<br/>
            <h:outputLabel>Nome: </h:outputLabel><h:inputText value="#{profController.professor.nmProfessor}"/><br/>
            <h:outputLabel>CPF: </h:outputLabel><h:inputText value="#{profController.professor.nrCpf}"/><br/>
            <h:outputLabel>E-Mail: </h:outputLabel><h:inputText value="#{profController.professor.nmEmail}"/><br/>
            <h:outputLabel>Telefone: </h:outputLabel><h:inputText value="#{profController.professor.nrTelefone}"/><br/>
            <h:commandButton value="Inserir Novo Professor"  actionListener="#{profController.inserirProfessor()}"  /><br/>
            <h:commandButton value="Modificar Dados"  actionListener="#{profController.atualizarProfessor()}"  /><br/>

            <h:outputLabel id="lblMensagem"  rendered="#{profController.alunoInserido}" style="color: red;" >
                <strong>#{profController.mensagem}</strong>
            </h:outputLabel><br/>
            <h:dataTable value="#{profController.professoresCadastrados}" var="alunoAtual" border="1" styleClass="order-table"  headerClass="order-table-header"  rowClasses="order-table-odd-row,order-table-even-row" >
                <h:column >
                    <f:facet name="header">Nome:</f:facet>
                    <h:commandLink value="#{alunoAtual.nmProfessor}" actionListener="#{profController.selecionarProfessor}" >
                        <f:param name="nrCpf" value="#{alunoAtual.nrCpf}"/>
                        <f:attribute name="numeroCpf" value="#{alunoAtual.nrCpf}" />
                    </h:commandLink>
                </h:column>
                <h:column >
                    <f:facet name="header">CPF: </f:facet>
                    <h:commandLink value="#{alunoAtual.nrCpf}" actionListener="#{profController.selecionarProfessor}" >
                        <f:param name="nrCpf" value="#{alunoAtual.nrCpf}"/>
                        <f:attribute name="numeroCpf" value="#{alunoAtual.nrCpf}" />
                    </h:commandLink>
                </h:column>
                <h:column >
                    <f:facet name="header">E-Mail: </f:facet>
                    <h:commandLink value="#{alunoAtual.nmEmail}" actionListener="#{profController.selecionarProfessor}" >
                        <f:param name="nrCpf" value="#{alunoAtual.nrCpf}"/>
                        <f:attribute name="numeroCpf" value="#{alunoAtual.nrCpf}" />
                    </h:commandLink>
                </h:column>
                <h:column >
                    <f:facet name="header">Telefone: </f:facet>
                    <h:commandLink value="#{alunoAtual.nrTelefone}" actionListener="#{profController.selecionarProfessor}" >
                        <f:param name="nrCpf" value="#{alunoAtual.nrCpf}"/>
                        <f:attribute name="numeroCpf" value="#{alunoAtual.nrCpf}" />
                    </h:commandLink>                    
                </h:column>
                <h:column >
                    <f:facet name="header">Excluir</f:facet>
                    <h:commandButton  actionListener="#{profController.excluirProfessor}" value="Excluir">
                        <f:attribute name="numeroCpf" value="#{alunoAtual.nrCpf}" />
                    </h:commandButton>
                </h:column>
                <h:column >
                    <f:facet name="header">Selecionar</f:facet>
                    <h:commandButton  actionListener="#{profController.selecionarProfessor}" value="Selecionar">
                        <f:attribute name="numeroCpf" value="#{alunoAtual.nrCpf}" />
                    </h:commandButton>
                </h:column>
            </h:dataTable>
        </h:form>
    </h:body>
</html>